name: Test-echo
on:
  issues:
    types: [opened]
jobs:
  test-echo:
    runs-on: ubuntu-latest
    env:
      t: ${{ secrets.T1 }}
    steps:
      - name: Test-Echo
        run: echo "$t"
      - name: Test1
        run: echo ${t:0:2}
